{
	"data": "ENC[AES256_GCM,data:hPIx8BBuekzdJKD7A5X8EyS+9oJkEhqq0Tbe02zymliwhsrdtCFwCkv/v3zs3wtYnJH9X3fjS2/lb5IhDQ+86atiy5XPzB9EmgMfcCBG7Zd0XgdSdCpar4A0lB4WivP1o2G+t8zKyNSoclJ87AnIdslJPKTQ277ySmEXw8jYZsXRXANCT3E0CC3YvrR/hh8pomCUM+F19R70qcUBEOyuseFHnHcnVAo7DMgXcFeqLcjdLYsVghp9VaPpP1No7/LkjpEmjCgyB46Hd9XtcLmCcbXFcKETOdyBgODSaNfuPknjcQfYnxZ4eaOBFoi3d0Yulg2hEtTwHCQO3nBFLf32bAnqGCGloE0Gfk55iGQcCmnFKYqL832D3n2FWd12xXAUfzSNayF3M+VF0ImaSgT9ivzId6xVndXBQ6PLXH/zPN6kXvaASCBm96VY7WnBlst4CN5A8YoKwxT3jUZY9um3KW3dRQ==,iv:Zae69prK9rYSCIvvWFGFczUTHjbX/vVrDl9ZWHpIP9Q=,tag:avI+Gs6fW1WVBee9GSYKtw==,type:str]",
	"sops": {
		"age": [
			{
				"recipient": "age1jghhfq9pjd6gzht3z8tc638hmpxuzu7w7avx4gmtheqwqczewe6qzvl4j2",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxdVY3Qm1NekFCc0lPcHIv\nbThVRzRQYlNXNTlWczZmU2YrT004c3hjMjJnCkVwVk4vTnhVMFFBVHNhU3ZJNDhk\ndy93ZlArOUQ3R1FTTUQ2Mk9LbVVBclEKLS0tIDlxV3B6Mi8zaEtqNWROSkVEUkhZ\na2dFdUthdXpjL1NsTGgzb3VVZnVBMlkKWZ8Q3VFhFCqS7ZDy5OSH2Wrch6KMUvv3\nNu1kxFnE59R5neVydyB9DjQZ0bM3EX5zCQy7wH/fUrJBGsdLFd4G+g==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2025-07-20T11:37:55Z",
		"mac": "ENC[AES256_GCM,data:NDO+Sx70zY3sMRvqLK+P8wd7+BKnqQ95IMaZQ/7hAOJkIBWsOpxziDyHJXW7q9+5Mzb7Twig6W0RPiNwsff929BG1ICWyZAVUz/oUbhRRo4iLAZuw/KJxBbO52XPvkGvtQfr999ZDiHCa0xffKWAHpOK5F7Ec7HW6AZLinTldk8=,iv:aEQPTshFrwf18RbQyKXFcFQcqXZ8twNUFEdrLxjzatE=,tag:UnEr9oVtQjhaXhMvBV+DFQ==,type:str]",
		"unencrypted_suffix": "_unencrypted",
		"version": "3.10.2"
	}
}
